<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SupportRequest;
use App\Models\User;

class SupportRequestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get users for assignment
        $instructors = User::where('role', 'instructor')->pluck('id')->toArray();
        $clients = ['client@zoswa.com', 'lisa@techcorp.com', 'mark@startup.io'];

        $supportRequests = [
            // Client requests
            [
                'name' => 'Robert Smith',
                'email' => 'client@zoswa.com',
                'phone' => '+1-555-0103',
                'country' => 'United States',
                'project_title' => 'E-commerce Website Development',
                'project_description' => 'Need help building a modern e-commerce website with payment integration, inventory management, and user authentication. The site should handle both B2B and B2C sales with different pricing tiers.',
                'project_type' => 'web_development',
                'urgency' => 'medium',
                'expected_timeframe' => '6-8 weeks',
                'project_duration' => '2 months',
                'budget_min' => 5000.00,
                'budget_max' => 10000.00,
                'technical_requirements' => 'React.js frontend, Node.js backend, PostgreSQL database, Stripe payment integration, AWS hosting',
                'status' => 'in_progress',
                'assigned_to' => !empty($instructors) ? $instructors[array_rand($instructors)] : null,
                'admin_notes' => 'Assigned to experienced web developer. Client has existing branding guidelines.',
                'responded_at' => now()->subDays(3),
                'created_at' => now()->subWeeks(2),
            ],
            [
                'name' => 'Robert Smith',
                'email' => 'client@zoswa.com',
                'phone' => '+1-555-0103',
                'country' => 'United States',
                'project_title' => 'Mobile App Bug Fixes',
                'project_description' => 'Critical bugs in existing React Native mobile application need immediate attention. App crashes on login and payment processing fails intermittently.',
                'project_type' => 'bug_fixing',
                'urgency' => 'urgent',
                'expected_timeframe' => '1-2 weeks',
                'project_duration' => '2 weeks',
                'budget_min' => 1000.00,
                'budget_max' => 2000.00,
                'technical_requirements' => 'React Native, Redux, Firebase authentication, Stripe payments',
                'status' => 'completed',
                'assigned_to' => !empty($instructors) ? $instructors[array_rand($instructors)] : null,
                'admin_notes' => 'Bugs fixed successfully. Payment processing issue resolved.',
                'responded_at' => now()->subDays(10),
                'created_at' => now()->subWeeks(3),
            ],
            [
                'name' => 'Lisa Corporate',
                'email' => 'lisa@techcorp.com',
                'phone' => '+1-555-0503',
                'country' => 'Canada',
                'project_title' => 'Team Training - Advanced React Development',
                'project_description' => 'Need comprehensive training program for our development team of 12 developers. Focus on advanced React patterns, performance optimization, and testing strategies.',
                'project_type' => 'consulting',
                'urgency' => 'medium',
                'expected_timeframe' => '3-4 weeks',
                'project_duration' => '1 month',
                'budget_min' => 8000.00,
                'budget_max' => 15000.00,
                'technical_requirements' => 'React 18+, TypeScript, Jest, React Testing Library, Performance monitoring tools',
                'status' => 'assigned',
                'assigned_to' => !empty($instructors) ? $instructors[array_rand($instructors)] : null,
                'admin_notes' => 'Large team training project. Will require multiple sessions.',
                'responded_at' => now()->subDays(1),
                'created_at' => now()->subWeeks(1),
            ],
            [
                'name' => 'Lisa Corporate',
                'email' => 'lisa@techcorp.com',
                'phone' => '+1-555-0503',
                'country' => 'Canada',
                'project_title' => 'API Development and Integration',
                'project_description' => 'Develop RESTful API for our internal systems integration. Need to connect CRM, inventory management, and accounting systems.',
                'project_type' => 'api_development',
                'urgency' => 'high',
                'expected_timeframe' => '4-6 weeks',
                'project_duration' => '2 months',
                'budget_min' => 6000.00,
                'budget_max' => 12000.00,
                'technical_requirements' => 'Node.js, Express, MongoDB, JWT authentication, Docker deployment',
                'status' => 'in_review',
                'assigned_to' => null,
                'admin_notes' => 'Reviewing technical requirements and timeline.',
                'responded_at' => null,
                'created_at' => now()->subDays(5),
            ],
            [
                'name' => 'Mark Startup',
                'email' => 'mark@startup.io',
                'phone' => '+1-555-0603',
                'country' => 'United States',
                'project_title' => 'MVP Development - SaaS Platform',
                'project_description' => 'Need to build minimum viable product for our SaaS platform. User management, subscription billing, analytics dashboard, and API for third-party integrations.',
                'project_type' => 'web_development',
                'urgency' => 'high',
                'expected_timeframe' => '8-12 weeks',
                'project_duration' => '3 months',
                'budget_min' => 15000.00,
                'budget_max' => 25000.00,
                'technical_requirements' => 'Next.js, Prisma, PostgreSQL, Stripe subscriptions, Vercel deployment, TypeScript',
                'status' => 'pending',
                'assigned_to' => null,
                'admin_notes' => null,
                'responded_at' => null,
                'created_at' => now()->subDays(2),
            ],
            [
                'name' => 'Mark Startup',
                'email' => 'mark@startup.io',
                'phone' => '+1-555-0603',
                'country' => 'United States',
                'project_title' => 'Database Design Consultation',
                'project_description' => 'Need expert advice on database architecture for high-traffic application. Expecting 100K+ users with complex relationship data.',
                'project_type' => 'database_design',
                'urgency' => 'medium',
                'expected_timeframe' => '2-3 weeks',
                'project_duration' => '3 weeks',
                'budget_min' => 3000.00,
                'budget_max' => 5000.00,
                'technical_requirements' => 'PostgreSQL, Redis caching, horizontal scaling, performance optimization',
                'status' => 'in_progress',
                'assigned_to' => !empty($instructors) ? $instructors[array_rand($instructors)] : null,
                'admin_notes' => 'Database architecture review in progress.',
                'responded_at' => now()->subDays(4),
                'created_at' => now()->subWeeks(1)->subDays(3),
            ],

            // Additional diverse requests
            [
                'name' => 'Tech Solutions Inc',
                'email' => 'contact@techsolutions.com',
                'phone' => '+1-555-0700',
                'country' => 'Australia',
                'project_title' => 'Legacy System Migration',
                'project_description' => 'Migrate legacy PHP application to modern Node.js stack. Application handles customer data and needs zero-downtime migration.',
                'project_type' => 'consulting',
                'urgency' => 'medium',
                'expected_timeframe' => '12-16 weeks',
                'project_duration' => '4 months',
                'budget_min' => 20000.00,
                'budget_max' => 35000.00,
                'technical_requirements' => 'Node.js, TypeScript, PostgreSQL, Docker, Kubernetes, CI/CD pipeline',
                'status' => 'pending',
                'assigned_to' => null,
                'admin_notes' => null,
                'responded_at' => null,
                'created_at' => now()->subDays(1),
            ],
            [
                'name' => 'StartupHub',
                'email' => 'dev@startuphub.co.uk',
                'phone' => '+44-20-7123-4567',
                'country' => 'United Kingdom',
                'project_title' => 'Mobile App Development - iOS & Android',
                'project_description' => 'Cross-platform mobile application for project management. Native performance required with offline capabilities.',
                'project_type' => 'mobile_app',
                'urgency' => 'high',
                'expected_timeframe' => '10-14 weeks',
                'project_duration' => '3.5 months',
                'budget_min' => 18000.00,
                'budget_max' => 30000.00,
                'technical_requirements' => 'Flutter or React Native, offline storage, push notifications, biometric authentication',
                'status' => 'assigned',
                'assigned_to' => !empty($instructors) ? $instructors[array_rand($instructors)] : null,
                'admin_notes' => 'Mobile development specialist assigned.',
                'responded_at' => now()->subHours(12),
                'created_at' => now()->subDays(3),
            ],
            [
                'name' => 'DataCorp Analytics',
                'email' => 'projects@datacorp.de',
                'phone' => '+49-30-12345678',
                'country' => 'Germany',
                'project_title' => 'Desktop Application - Data Visualization',
                'project_description' => 'Desktop application for complex data visualization and analysis. Must handle large datasets (10M+ records) with real-time updates.',
                'project_type' => 'desktop_app',
                'urgency' => 'medium',
                'expected_timeframe' => '8-10 weeks',
                'project_duration' => '2.5 months',
                'budget_min' => 12000.00,
                'budget_max' => 20000.00,
                'technical_requirements' => 'Electron.js, D3.js, WebGL, SQLite, Python integration for data processing',
                'status' => 'completed',
                'assigned_to' => !empty($instructors) ? $instructors[array_rand($instructors)] : null,
                'admin_notes' => 'Successfully delivered. Client very satisfied with performance.',
                'responded_at' => now()->subDays(20),
                'created_at' => now()->subMonths(2),
            ],
            [
                'name' => 'CodeReview Pro',
                'email' => 'quality@codereview.pro',
                'phone' => '+1-555-0800',
                'country' => 'Canada',
                'project_title' => 'Code Review and Optimization',
                'project_description' => 'Comprehensive code review for large React application. Performance issues and security concerns need addressing.',
                'project_type' => 'code_review',
                'urgency' => 'low',
                'expected_timeframe' => '2-3 weeks',
                'project_duration' => '3 weeks',
                'budget_min' => 2500.00,
                'budget_max' => 4000.00,
                'technical_requirements' => 'React, TypeScript, Node.js, security audit tools, performance profiling',
                'status' => 'cancelled',
                'assigned_to' => null,
                'admin_notes' => 'Client cancelled due to budget constraints.',
                'responded_at' => now()->subDays(7),
                'created_at' => now()->subWeeks(2)->subDays(1),
            ],
        ];

        foreach ($supportRequests as $requestData) {
            SupportRequest::create($requestData);
        }

        $this->command->info('Support requests seeded successfully!');
        $this->command->info('Created ' . count($supportRequests) . ' support requests with various statuses and types.');
        $this->command->info('Requests include: pending, in_review, assigned, in_progress, completed, and cancelled statuses.');
    }
}